### ISSUE TITLE
Lentidão

### ISSUE THREAD

**Issue by staticdev** [thiagootuler/ugcnormal_interface#4]
Olá,

Estou utilizando o normalizador para um chatbot que desenvolvo para o mestrado e as chamadas estão muito lentas. Por acaso você possui o código do webservice para eu levantar ele localmente?

Abracos,

Thiago D'Ávila

**Comment by avanco** [comment]
Olá Thiago

O repositório do normalizador: https://github.com/avanco/UGCNormal

Pode utilizá-lo diretamente, sem instanciar o web-service.

Abraço, 
Lucas

**Comment by staticdev** [comment]
@avanco essa solução resolveria também, mas minha aplicação funciona em containers. O ideal realmente seria usar a interface e subir o webservice localmente. Caso seja possível disponibilizar o código do webserviço seria ótimo. Caso não seja possível, terei que criar meu próprio webservice (o que daria mais trabalho).

**Comment by avanco** [comment]
Entendi...
Posso adicionar ao repositório o web-service

**Comment by staticdev** [comment]
=)

Vi que vc fez um ws soap. Como contribuição posso fazer uma versão Rest dele tb.

**Comment by staticdev** [comment]
=)

Vi que vc fez um ws soap. Como contribuição posso fazer uma versão Rest dele tb.

**Comment by staticdev** [comment]
@avanco estamos com um deadline na UFMG um pouco apertado para comparação dos métodos de normalização (para semana que vem). Não conseguimos integrar o https://github.com/avanco/UGCNormal, pois ele trabalha com arquivos e é escrito em Perl. Nosso sistema é em Python/C e normaliza frases direto.

Gostaríamos muito de colocar o UGCNormal na comparação através de um webservice local. Você tem previsão de quando seria possível a disponibilização do código?

**Comment by carolcoimbra** [comment]
@avanco 
você acha que consegue disponibilizaro código até o fim dessa semana? Estamos com um prazo muito corrido e, da forma como o UGCNormal funciona hoje não está sendo muito viável pra gente já que precisamos normalizar frases curtas e está levando muito tempo :/

Muito obrigada

**Comment by thiagootuler** [comment]
Olá pessoal
Tomei a liberdade de desenvolver um [webservice](https://github.com/thiagootuler/ugcnormal_interface/tree/master/local_webservice) para que vocês possam usar o normalizador localmente. Não melhorou muito a velocidade de resposta do normalizador, pois o gargalo esta no speller, mas já permite que vocês utilizem os recursos do normalizador separadamente.
Espero que ajude vocês!

**Comment by staticdev** [comment]
Muito obrigado @thiagootuler! Iremos testar e retornamos.

**Comment by carolcoimbra** [comment]
@thiagootuler 
coloquei o arquivo api_server.py na pasta do UGCNormal depois de configurar e quando eu rodo o exemplo de uso aparece o seguinte erro:

![captura de tela de 2018-01-16 17-05-09](https://user-images.githubusercontent.com/11412595/35007067-970e4402-fadf-11e7-9a0f-5baf7935214f.png)

**Comment by staticdev** [comment]
Também testei em outra máquina só que usando Python 2.7 e não funcionou. Depois de adicionar a linha de debug abaixo apareceu o mesmo erro:

```
app = Flask(__name__)
app.config['DEBUG'] = True
```

![image](https://user-images.githubusercontent.com/1446633/35010356-c2a30206-fae9-11e7-805d-40b901846242.png)

**Comment by thiagootuler** [comment]
Olá pessoal
Fiz uma [modificação](https://github.com/thiagootuler/ugcnormal_interface/commit/829a0d606e66f4ac68edf1ad674aea68ffafa663) no fonte do [api_server.py](https://github.com/thiagootuler/ugcnormal_interface/blob/master/local_webservice/api_server.py)  que corrigirá esse problema.
Espero que vocês ainda tenha tempo de testar o normalizador.
Desculpe a demora na responta.

**Comment by staticdev** [comment]
@thiagootuler agora na hora de rodar o /spell estou tomando um erro:
`Can't open perl script "./spell.pl": No such file or directory`. Veja se esse erro ocorre para você. Imagino que seja por que ele está na pasta 'speller' do UGCNormal.

**Comment by staticdev** [comment]
Ainda estamos tomando alguns erros relativos aos caminhos dos scripts perl. Mandei um pull request (#6) com alguns caminhos diferentes da estrutura do avanco/UGCNormal. Porém, acredito que para manter compatibilidade com o caminho do speller no código dele, o api_server.py deveria ser colocado em um nível abaixo de uma pasta ugc_norm (https://github.com/avanco/UGCNormal/blob/master/speller/spell.pl).

**Comment by thiagootuler** [comment]
@staticdev fiz uma alteração no server e agora to passando o caminho completo para o speller. Aqui funcionou dessa forma também, teste ai e me de um retorno depois.
Por enquanto vamos manter o server na raiz do UGCNormal para não requerer outras modificações.

**Comment by staticdev** [comment]
@thiagootuler fiz algumas otimizacoes e coloquei no docker um microsservico para o uso através de chamadas rest: https://github.com/staticdev/ugcnormal-microservice
